import { ObjectTypes } from "../../../@types/index.js";

export const AnalogEvent = {
    Csig_All_Audio_Volume: "Csig.All_Audio_Volume",
    Csig_Auto_Answer_Delay: "Csig.Auto_Answer_Delay",
    Csig_BlueLedBlinkTime: "Csig.BlueLedBlinkTime",
    Csig_BlueLedBrightness: "Csig.BlueLedBrightness",
    Csig_BlueStatusBarBlinkTime: "Csig.BlueStatusBarBlinkTime",
    Csig_BlueStatusBarBrightness: "Csig.BlueStatusBarBrightness",
    Csig_Button_Toolbar_Display_Edge: "Csig.Button_Toolbar_Display_Edge",
    Csig_Button_Toolbar_Display_Timeout: "Csig.Button_Toolbar_Display_Timeout",
    Csig_Camera_Preset: "Csig.Camera_Preset",
    Csig_Capture_color_mode: "Csig.Capture_color_mode",
    Csig_Conf_Mic_Vol: "Csig.Conf_Mic_Vol",
    Csig_Conf_Spkr_Vol: "Csig.Conf_Spkr_Vol",
    Csig_Default_Spkr_Vol: "Csig.Default_Spkr_Vol",
    Csig_Display_Orientation_Config: "Csig.Display_Orientation_Config",
    Csig_Docked_Standby_Timeout: "Csig.Docked_Standby_Timeout",
    Csig_GreenLedBlinkTime: "Csig.GreenLedBlinkTime",
    Csig_GreenLedBrightness: "Csig.GreenLedBrightness",
    Csig_GreenStatusBarBlinkTime: "Csig.GreenStatusBarBlinkTime",
    Csig_GreenStatusBarBrightness: "Csig.GreenStatusBarBrightness",
    Csig_Hard_Button_Brightness: "Csig.Hard_Button_Brightness",
    Csig_Hard_Button_Brt_Auto_Thresh: "Csig.Hard_Button_Brt_Auto_Thresh",
    Csig_Image_Mode: "Csig.Image_Mode",
    Csig_Key_Backlight_High: "Csig.Key_Backlight_High",
    Csig_Key_Backlight_Low: "Csig.Key_Backlight_Low",
    Csig_Key_Click_Volume: "Csig.Key_Click_Volume",
    Csig_Lcd_Brt: "Csig.Lcd_Brt",
    Csig_Lcd_Brt_Auto_Thresh: "Csig.Lcd_Brt_Auto_Thresh",
    Csig_LCD_Level_High: "Csig.LCD_Level_High",
    Csig_LCD_Level_Lo: "Csig.LCD_Level_Lo",
    Csig_LCD_Level_Med: "Csig.LCD_Level_Med",

    Csig_Poll_Interval: "Csig.Poll_Interval",
    Csig_Polycom_TT_Enable_Analog_: "Csig.Polycom_TT_Enable_Analog_",
    Csig_Polycom_TT_Frame_Size_Analog_: "Csig.Polycom_TT_Frame_Size_Analog_",
    Csig_Polycom_TT_Sensitivity_Analog: "Csig.Polycom_TT_Sensitivity_Analog",
    Csig_Power_Timeout: "Csig.Power_Timeout",
    Csig_RedLedBlinkTime: "Csig.RedLedBlinkTime",
    Csig_RedLedBrightness: "Csig.RedLedBrightness",
    Csig_RedStatusBarBlinkTime: "Csig.RedStatusBarBlinkTime",
    Csig_RedStatusBarBrightness: "Csig.RedStatusBarBrightness",
    Csig_Screensaver_Logo_Setting: "Csig.Screensaver_Logo_Setting",
    Csig_Standby_Timeout: "Csig.Standby_Timeout",
    Csig_System_Media_Volume: "Csig.System_Media_Volume",
    Csig_TIMEZONE_INDEX: "Csig.TIMEZONE_INDEX",
    Csig_UCENGINE_auto_zoom_mode: "Csig.UCENGINE_auto_zoom_mode",
    Csig_UCENGINE_auto_zoom_speed: "Csig.UCENGINE_auto_zoom_speed",
} as const;

export type AnalogEvent = ObjectTypes<typeof AnalogEvent>;

export default AnalogEvent;
